import 'package:flutter/material.dart';
void main()=>runApp(const Daka());
class Daka extends StatelessWidget{const Daka({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(useMaterial3:true,colorSchemeSeed:const Color(0xff335cff)),home:const App());}
class App extends StatefulWidget{const App({super.key});@override State<App> createState()=>_AppState();}
class _AppState extends State<App>{int tab=0;double capital=10000,target=10;final months=[['يناير',12.4],['فبراير',8.2],['مارس',15.1],['أبريل',-2.3],['مايو',11.8],['يونيو',10.6]];@override Widget build(BuildContext c){final pages=[Home(capital,target,months),Editor((a,b)=>setState((){capital=a;target=b;tab=0;})),Stats(months),Calc(capital)];return Directionality(textDirection:TextDirection.rtl,child:Scaffold(body:SafeArea(child:pages[tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),label:'الرئيسية'),NavigationDestination(icon:Icon(Icons.add),label:'إضافة'),NavigationDestination(icon:Icon(Icons.bar_chart),label:'الإحصائيات'),NavigationDestination(icon:Icon(Icons.calculate),label:'الحاسبة')])));}}
class Head extends StatelessWidget{final String a,b;const Head(this.a,this.b,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold)),Text(b,style:TextStyle(color:Colors.grey.shade600))]));}
class Home extends StatelessWidget{final double cap,t;final List<List<dynamic>> ms;const Home(this.cap,this.t,this.ms,{super.key});@override Widget build(BuildContext c){final p=ms.last[1] as double;final left=cap*t/100-cap*p/100;return ListView(children:[const Head('أهلاً بك في دكا','نظرة سريعة على أداء تداولك'),Card(margin:const EdgeInsets.symmetric(horizontal:20),child:Padding(padding:const EdgeInsets.all(20),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('أداء ${ms.last[0]}',style:const TextStyle(fontWeight:FontWeight.bold)),Text('$p%',style:const TextStyle(fontSize:42,fontWeight:FontWeight.bold,color:Color(0xff335cff))),LinearProgressIndicator(value:(p/t).clamp(0,1),minHeight:10),const SizedBox(height:12),Text(left>0?'متبقي ${left.toStringAsFixed(0)} للوصول للهدف':'تجاوزت الهدف بـ ${(-left).toStringAsFixed(0)} 🎉')])),),Padding(padding:const EdgeInsets.all(20),child:Row(children:[Expanded(child:Info('رأس المال','${cap.toStringAsFixed(0)} ر.س',Icons.wallet)),const SizedBox(width:12),Expanded(child:Info('الهدف الشهري','$t%',Icons.flag))])),const Padding(padding:EdgeInsets.symmetric(horizontal:20),child:Text('الأشهر الأخيرة',style:TextStyle(fontSize:18,fontWeight:FontWeight.bold))),...ms.reversed.map((m)=>ListTile(leading:CircleAvatar(child:Icon((m[1] as double)>=t?Icons.check:Icons.close)),title:Text(m[0]),trailing:Text('${m[1]}%',style:TextStyle(fontWeight:FontWeight.bold,color:(m[1] as double)>=0?Colors.green:Colors.red))))]);}}
class Info extends StatelessWidget{final String a,b;final IconData i;const Info(this.a,this.b,this.i,{super.key});@override Widget build(BuildContext c)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:const Color(0xff335cff)),Text(a),Text(b,style:const TextStyle(fontWeight:FontWeight.bold))])));}
class Editor extends StatelessWidget{final void Function(double,double) save;const Editor(this.save,{super.key});@override Widget build(BuildContext c){final a=TextEditingController(text:'10000'),b=TextEditingController(text:'10');return ListView(padding:const EdgeInsets.all(20),children:[const Head('إضافة بيانات','حدّث رأس مالك وهدفك'),Field('رأس المال',a,Icons.wallet),Field('نسبة الهدف',b,Icons.percent),const SizedBox(height:20),FilledButton(onPressed:()=>save(double.tryParse(a.text)??10000,double.tryParse(b.text)??10),child:const Text('حفظ البيانات'))]);}}
class Field extends StatelessWidget{final String s;final TextEditingController x;final IconData i;const Field(this.s,this.x,this.i,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:16),child:TextField(controller:x,keyboardType:TextInputType.number,decoration:InputDecoration(labelText:s,prefixIcon:Icon(i),filled:true,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide.none))));}
class Stats extends StatelessWidget{final List<List<dynamic>> ms;const Stats(this.ms,{super.key});@override Widget build(BuildContext c){final avg=ms.map((x)=>x[1] as double).reduce((a,b)=>a+b)/ms.length;return ListView(padding:const EdgeInsets.all(20),children:[const Head('الإحصائيات','تابع تطور أدائك'),Info('متوسط الربح','${avg.toStringAsFixed(1)}%',Icons.insights),Info('أشهر ناجحة','${ms.where((x)=>(x[1] as double)>=10).length} من ${ms.length}',Icons.verified)]);}}
class Calc extends StatefulWidget{final double cap;const Calc(this.cap,{super.key});@override State<Calc> createState()=>_CalcState();}class _CalcState extends State<Calc>{int years=1;final a=TextEditingController(text:'10000'),r=TextEditingController(text:'10');@override Widget build(BuildContext c){final p=double.tryParse(a.text)??0,rate=(double.tryParse(r.text)??0)/100,total=p;return ListView(padding:const EdgeInsets.all(20),children:[const Head('حاسبة الأرباح','خطط لنمو رأس مالك'),Field('رأس المال',a,Icons.savings),Field('النسبة الشهرية',r,Icons.percent),Wrap(spacing:8,children:[1,2,3,4,5].map((x)=>ChoiceChip(label:Text('$x سنوات'),selected:years==x,onSelected:(_){setState(()=>years=x);},)).toList()),const SizedBox(height:20),Info('رأس المال المتوقع','${(total*(1+rate*12*years)).toStringAsFixed(0)} ر.س',Icons.trending_up),Text('الربح المطلوب شهرياً: ${(p*rate).toStringAsFixed(0)} ر.س')]);}}
